import { BaseAdapter } from './BaseAdapter.js';

export class GovernmentScholarshipsAdapter extends BaseAdapter {
  constructor() {
    super('src-gov-global', 'Global Government Scholarship Portals', 'gov.scholarships', 1);
  }

  async parse() {
    return [
      {
        id: 'chevening-uk-2027',
        title: 'Chevening UK Government Master’s Scholarships 2027',
        organization: 'UK Foreign, Commonwealth & Development Office (FCDO)',
        location_country: 'United Kingdom',
        location_city: 'London / Oxford / Cambridge / Edinburgh',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'masters',
        field_of_study: 'advertising',
        funding_level: 'fully_funded',
        stipend_text: '100% Tuition Fees + £1,400/mo Living Stipend + Return Flight',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2026-11-05',
        deadline_raw: 'November 5, 2026',
        no_ielts: 1,
        is_popular: 1,
        official_apply_url: 'https://www.chevening.org/scholarships/',
        official_program_url: 'https://www.chevening.org/',
        description: 'The UK government’s global scholarship programme offering future leaders a one-year fully funded Master’s degree at any UK university in Advertising, Media, Business, Tech, or Public Relations.',
        benefits_summary: 'Full university tuition fees, a monthly living allowance (£1,400/mo in London), economy return flights to the UK, and arrival allowance.',
        eligibility_summary: 'Undergraduate degree (Bachelor), at least 2 years of work experience, return to country of citizenship for at least 2 years after study.',
        trust_score: 100,
        quality_score: 99,
        verification_status: 'official_verified'
      },
      {
        id: 'erasmus-mundus-2027',
        title: 'Erasmus Mundus Joint Master Degrees (EMJM)',
        organization: 'European Commission (Erasmus+)',
        location_country: 'European Union (Multiple Countries)',
        location_city: 'Paris, Rome, Berlin & Amsterdam',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'masters',
        field_of_study: 'advertising',
        funding_level: 'fully_funded',
        stipend_text: '€1,400 / month + 100% Tuition + €3,000 Travel Grant',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2027-01-15',
        deadline_raw: 'January 15, 2027',
        no_ielts: 1,
        is_popular: 1,
        official_apply_url: 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters',
        official_program_url: 'https://erasmus-plus.ec.europa.eu/',
        description: 'Prestigious integrated international study programmes delivered jointly by a consortium of higher education institutions in Europe. Students study in at least two different European countries.',
        benefits_summary: 'Full participation costs waiver, €1,400/month individual living allowance, and up to €3,000/year travel & installation allowance.',
        eligibility_summary: 'Students worldwide who hold a Bachelor degree or demonstrate equivalent learning.',
        trust_score: 100,
        quality_score: 99,
        verification_status: 'official_verified'
      },
      {
        id: 'fulbright-foreign-student-2027',
        title: 'Fulbright Foreign Student Program (USA)',
        organization: 'U.S. Department of State / Bureau of Educational and Cultural Affairs',
        location_country: 'United States',
        location_city: 'Leading US Universities',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'masters',
        field_of_study: 'social',
        funding_level: 'fully_funded',
        stipend_text: '100% US Tuition + Monthly Living Stipend + J-1 Visa Sponsorship',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2026-10-15',
        deadline_raw: 'October 15, 2026',
        no_ielts: 0,
        is_popular: 1,
        official_apply_url: 'https://foreign.fulbrightonline.org/about/foreign-student-program',
        official_program_url: 'https://foreign.fulbrightonline.org/',
        description: 'Enables graduate students, young professionals, and artists from abroad to study and conduct research in the United States at top institutions.',
        benefits_summary: 'Full tuition, round-trip airfare to the USA, monthly living stipend, and comprehensive health benefit plan.',
        eligibility_summary: 'Completed undergraduate education (Bachelor degree) and have a strong academic background.',
        trust_score: 100,
        quality_score: 99,
        verification_status: 'official_verified'
      },
      {
        id: 'mext-japan-gov-2027',
        title: 'MEXT Japan Ministry of Education Government Scholarships',
        organization: 'Ministry of Education, Culture, Sports, Science and Technology (MEXT)',
        location_country: 'Japan',
        location_city: 'Tokyo, Kyoto, Osaka',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'undergrad',
        field_of_study: 'advertising',
        funding_level: 'fully_funded',
        stipend_text: '¥144,000 / month + 100% Tuition + Tokyo Round-Trip Flight',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2026-06-15',
        deadline_raw: 'June 15, 2026',
        no_ielts: 1,
        is_popular: 1,
        official_apply_url: 'https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/',
        official_program_url: 'https://www.studyinjapan.go.jp/',
        description: 'Premier Japanese Government scholarship providing full tuition, round-trip airfare, and monthly stipend for international students to study at leading Japanese universities.',
        benefits_summary: '100% exemption from entrance exam fees and tuition, round-trip international flight ticket to Tokyo, ¥144,000 monthly living stipend.',
        eligibility_summary: 'Applicants with foreign nationality who have completed 12 years of school education or Bachelor graduates.',
        trust_score: 100,
        quality_score: 99,
        verification_status: 'official_verified'
      },
      {
        id: 'france-eiffel-2027',
        title: 'Campus France Eiffel Excellence Scholarship Programme',
        organization: 'French Ministry for Europe and Foreign Affairs',
        location_country: 'France',
        location_city: 'Paris, Lyon, Marseille',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'masters',
        field_of_study: 'advertising',
        funding_level: 'fully_funded',
        stipend_text: '€1,181 / month + Round-trip Airfare + French Health Insurance',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2027-01-10',
        deadline_raw: 'January 10, 2027',
        no_ielts: 1,
        is_popular: 1,
        official_apply_url: 'https://www.campusfrance.org/en/the-eiffel-scholarship-program',
        official_program_url: 'https://www.campusfrance.org/',
        description: 'Developed by the Ministry of Foreign Affairs to allow French higher education institutions to attract top foreign students for Master’s and PhD programs.',
        benefits_summary: 'Monthly allowance of €1,181, international air travel, train travel within France, local transport, health insurance, and cultural activities.',
        eligibility_summary: 'Non-French nationality applicants up to 25 years old for Master level.',
        trust_score: 100,
        quality_score: 99,
        verification_status: 'official_verified'
      },
      {
        id: 'turkiye-burslari-2027',
        title: 'Türkiye Bursları Full Government Scholarship Program',
        organization: 'Presidency for Turks Abroad and Related Communities (YTB)',
        location_country: 'Türkiye',
        location_city: 'Istanbul & Ankara',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'undergrad',
        field_of_study: 'advertising',
        funding_level: 'fully_funded',
        stipend_text: '100% Tuition + Free Dormitory Housing + Monthly Stipend + Flight',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2027-02-20',
        deadline_raw: 'February 20, 2027',
        no_ielts: 1,
        is_popular: 1,
        official_apply_url: 'https://www.turkiyeburslari.gov.tr/',
        official_program_url: 'https://www.turkiyeburslari.gov.tr/',
        description: 'Comprehensive competitive government scholarship program in Türkiye covering university placement, tuition, housing, health insurance, and Turkish language courses.',
        benefits_summary: 'Free university tuition, free state dormitory accommodation, monthly cash stipend, round-trip flight ticket, full health insurance coverage.',
        eligibility_summary: 'Open to citizens of all countries across Bachelor, Master, and PhD levels with minimum 70% GPA.',
        trust_score: 100,
        quality_score: 98,
        verification_status: 'official_verified'
      },
      {
        id: 'korea-gks-2027',
        title: 'Global Korea Scholarship (GKS / KGSP) 2027',
        organization: 'National Institute for International Education (NIIED)',
        location_country: 'South Korea',
        location_city: 'Seoul & National Universities',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'undergrad',
        field_of_study: 'advertising',
        funding_level: 'fully_funded',
        stipend_text: '1,000,000 KRW / month + 100% Tuition + Flight + Settlement Grant',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2026-10-20',
        deadline_raw: 'October 20, 2026',
        no_ielts: 1,
        is_popular: 1,
        official_apply_url: 'https://www.studyinkorea.go.kr/en/scholarship/gks_introduce.do',
        official_program_url: 'https://www.studyinkorea.go.kr/',
        description: 'Korean government scholarship designed to provide international students with opportunities to conduct advanced studies at higher educational institutions in South Korea.',
        benefits_summary: 'Full tuition fees, round-trip economy airfare, 1,000,000 KRW monthly stipend, 200,000 KRW settlement allowance, full medical insurance.',
        eligibility_summary: 'Both applicant and parents must be citizens of their country of origin (not Korea) and hold a cumulative GPA above 80%.',
        trust_score: 100,
        quality_score: 99,
        verification_status: 'official_verified'
      },
      {
        id: 'singapore-singa-2027',
        title: 'Singapore International Graduate Award (SINGA PhD)',
        organization: 'Agency for Science, Technology and Research (A*STAR)',
        location_country: 'Singapore',
        location_city: 'NUS, NTU & SUTD Campuses',
        is_remote: 0,
        type: 'scholarship',
        degree_level: 'phd',
        field_of_study: 'stem',
        funding_level: 'fully_funded',
        stipend_text: 'S$2,700 - S$3,200 / month + Full Tuition + S$1,500 Airfare Grant',
        tuition_covered: 1,
        travel_covered: 1,
        housing_covered: 1,
        deadline_utc: '2026-12-01',
        deadline_raw: 'December 1, 2026',
        no_ielts: 1,
        is_popular: 1,
        official_apply_url: 'https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa',
        official_program_url: 'https://www.a-star.edu.sg/',
        description: 'Collaboration between A*STAR, NTU, NUS, and SUTD to provide PhD training in top Singapore labs with world-renowned researchers.',
        benefits_summary: 'Full tuition fees coverage, monthly stipend of S$2,700 (increasing to S$3,200 after qualifying exam), one-time airfare grant of up to S$1,500, one-time settling-in allowance of S$1,000.',
        eligibility_summary: 'Open to all international graduates with a passion for research and excellent academic results.',
        trust_score: 100,
        quality_score: 99,
        verification_status: 'official_verified'
      }
    ];
  }
}
